/*
Datum laatste update: 31-03-17
Projectgroep 12: Enrico Schmitz, Thomas Reinders en Rick Beeloo
Functionaliteit: De gebruiker kan een FASTA bestand inladen. In de sequentie
			     kunnen vervolgens ORF's gezocht worden die verder geannoteerd 
			     kunnen worden door gebruikt te maken van een BLAST search.
Bekende bugs:    Als de gebruiker het tijdelijke BLAST bestand verwijderd zal de
                 data niet opgeslagen kunnen worden in de database.
 */
package AnnotationViewer.GUI;

import AnnotationViewer.Blast.BlastJobManager;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author projectgroep 12
 */
public class GUI extends javax.swing.JFrame {

    //instantie variable
    private final ActionHandler actionHandler = new ActionHandler();
 
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        actionHandler.saveChoiceAction("Should the data be saved to the database?", "OPTION");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. SOME OF THE GENERATED CODE IS ADJUSTED
     * USING THE COSTUMIZE CODE OPTION IN THE GUI BUILDER!
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sequentieScrollPane = new javax.swing.JScrollPane();
        readingFrameTextArea = new javax.swing.JTextArea();
        readingFrameLabel = new javax.swing.JLabel();
        blastTableLabel = new javax.swing.JLabel();
        blastTabelScrollPane = new javax.swing.JScrollPane();
        blastOutputTable = new javax.swing.JTable();
        headerLabel = new javax.swing.JLabel();
        seperatorLine = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        menuOpenButton = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSearchButton = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AnnotationViewer");

        readingFrameTextArea.setColumns(20);
        readingFrameTextArea.setRows(5);
        sequentieScrollPane.setViewportView(readingFrameTextArea);
        //make everything transparent except for the text
        sequentieScrollPane.setOpaque(false);
        sequentieScrollPane.getViewport().setOpaque(false);
        sequentieScrollPane.setBorder(null);
        sequentieScrollPane.setViewportBorder(null);
        readingFrameTextArea.setBackground(new Color(0, 0, 0, 0));
        readingFrameTextArea.setBorder(null);
        readingFrameTextArea.getAccessibleContext().setAccessibleName("readingFrameTextArea");
        readingFrameTextArea.getAccessibleContext().setAccessibleDescription("");

        readingFrameLabel.setText("<html><b>Reading frame sequences:</b></html>");

        blastTableLabel.setText("<html><b>BLAST jobs:</b></html>");

        DefaultTableModel tableModel = new DefaultTableModel (
            new Object [][] {

            },
            new String [] {
                "ORF ID", "BLAST result link"
            }
        )
        {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        blastOutputTable.setModel(tableModel);
        blastTabelScrollPane.setViewportView(blastOutputTable);
        blastOutputTable.getAccessibleContext().setAccessibleName("blastJobTable");

        headerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header.JPG"))); // NOI18N

        menuOpenButton.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/openIcon.png"))); // NOI18N
        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuOpenButton.add(jMenuItem1);

        menuBar.add(menuOpenButton);

        menuSearchButton.setText("Search");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoekIcoon.png"))); // NOI18N
        jMenuItem2.setText("ORF's");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuSearchButton.add(jMenuItem2);

        menuBar.add(menuSearchButton);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seperatorLine, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sequentieScrollPane)
                    .addComponent(blastTabelScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(readingFrameLabel)
                            .addComponent(blastTableLabel))
                        .addGap(0, 625, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperatorLine, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(readingFrameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sequentieScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blastTableLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blastTabelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Deze methode wordt aangeroepen als de gebruiker op de "open" menu optie
     * klikt.
     *
     * @param evt Een actionEvent.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        actionHandler.parseFile();
        actionHandler.calcRFs();
        actionHandler.showProteinRFs(readingFrameTextArea);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Deze methode wordt aangeroepen als de gebruiker op de "ORF" menu optie
     * klikt.
     *
     * @param evt Een actionEvent.
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        actionHandler.searchORFs();
        actionHandler.highLightORFs(readingFrameTextArea);
        BlastJobManager.setOutputTable(blastOutputTable);
        actionHandler.ResultCheckAction();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    /**
     * Deze methode zorgt voor het weergeven van de GUI.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable blastOutputTable;
    private javax.swing.JScrollPane blastTabelScrollPane;
    private javax.swing.JLabel blastTableLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuOpenButton;
    private javax.swing.JMenu menuSearchButton;
    private javax.swing.JLabel readingFrameLabel;
    private javax.swing.JTextArea readingFrameTextArea;
    private javax.swing.JSeparator seperatorLine;
    private javax.swing.JScrollPane sequentieScrollPane;
    // End of variables declaration//GEN-END:variables
}
